frappe/erpnext_com

erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/payment.md
erpnext_com/www/pricing/vip.md

Added ERPNext VIP

---

erpnext_com/www/download.html

Updated downloads page for new builds

---

erpnext_com/erpnext_com/doctype/conference_participant/conference_participant.py

Fix for razorpay payment capturing issue .

[minor][fix] typo fix

---

erpnext_com/api.py
erpnext_com/erpnext_com/doctype/conference_participant/conference_participant.py

Depends on https://github.com/frappe/frappe/pull/1968

[fix] update checkut url

---

erpnext_com/api.py

depends on : https://github.com/frappe/frappe/pull/2831

a[fix] provisions to cope with new payment handler

---

erpnext_com/api.py
erpnext_com/templates/includes/industry_footer.html
erpnext_com/templates/includes/macros.html
erpnext_com/www/distribution.html
erpnext_com/www/index.html
erpnext_com/www/manufacturing.html
erpnext_com/www/pricing/index.html
erpnext_com/www/retail.html
erpnext_com/www/schools.html
erpnext_com/www/services.html
erpnext_com/www/testimonials.html

[fix] remove free plan

---

erpnext_com/api.py
erpnext_com/templates/includes/signup.js
erpnext_com/www/signup.html
erpnext_com/www/signup.py

Signup redesign

---

erpnext_com/templates/includes/signup.js

[fix] set only subdomain while redirected from archived site

---

erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/payment.md

pricing updated for new plans

---

erpnext_com/templates/includes/custom.css
erpnext_com/templates/includes/macros.html
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

Pull active plans from central to display on Pricing page

---

erpnext_com/templates/includes/macros.html
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

* Pricing for users fom India
---
* Pricing for users from other countries

[enhance] show plan prices in currency INR if visitor is from india

---

erpnext_com/www/uae-ksa-vat.html

* Added new features for POS and Itemised Tax breakup thanks to @umairsy

added POS and itemised tax breakup

---

erpnext_com/templates/includes/footer/footer.html

fix india gst link

---

erpnext_com/templates/includes/signup.js

https://github.com/frappe/erpnext/issues/12828

[fix] regex fix for subdomain

---

erpnext_com/templates/includes/custom.css
erpnext_com/templates/includes/signup.js
erpnext_com/www/compare.html
erpnext_com/www/contact.html
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

New Pricing Plans

---

erpnext_com/www/pricing/index.py

Correct order of the features

---

erpnext_com/www/index.css

fix min height issue for the homepage illustration

Fix min-height issue on mobile

---

erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/support.html

Add old sections

---

erpnext_com/www/pricing/index.py

Add the 5 user plan

---

erpnext_com/templates/includes/custom.css
erpnext_com/www/pricing/index.html

This PR removes the cards and p10 user plan
Fixes [#13508](https://github.com/frappe/erpnext/issues/13508)
P.S. I would need help in making the hr between plans small as in my initial design, the design is shown in the issue.

Add new pricing update

---

erpnext_com/www/reporting-security-vulnerabilities.md

Reporting Security Vulnerabilities

---

erpnext_com/www/privacy.md

* Fixed spelling of 'compliant'
* Adding more elaboration regarding who will these policies affect
* Explanation why billing details cannot be deleted.

Fixing spellings + some more elaboration

---

erpnext_com/www/privacy.md

Updated after legal opinion on the same.

GDPR - Privacy Policy Updates

---

erpnext_com/www/privacy.md

Improving on the previous PR, this PR makes the links work like the ones on Github by sectionizing the questions.
You can access a question directly by using '#' followed by the section text

Fixed the Links on Headers and Questions

---

erpnext_com/templates/includes/signup.js
erpnext_com/www/pricing/index.py
erpnext_com/www/signup.html

https://github.com/frappe/central/pull/491

Signup fixes

---

erpnext_com/www/pricing/index.html

The link to 'Learn more about our enterprise plan' was broken. Fixed it.

Updated /pricing webpage

---

erpnext_com/templates/includes/custom.css
erpnext_com/templates/includes/subscription.js
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py
erpnext_com/www/signup.html

[UI] Signup page and pricing page fixes

---

erpnext_com/www/index.html
erpnext_com/www/pricing/index.py

1. Fix plan labels
2. Redirect to pricing page

[fix] Multiple Fixes

---

erpnext_com/api.py
erpnext_com/templates/includes/subscription.js
erpnext_com/www/signup.html

[signup form] add lang, country, tz, currency

---

erpnext_com/public/js/payment.js
erpnext_com/www/index.html
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

Paywalls:
and remove intercom on_update
Also mention 14-day trials:

[pricing] update paywalls and add Trial duration

---

erpnext_com/www/index.html
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py
erpnext_com/www/support/index.html

Add Enterprise and highlight Standard plan

---

erpnext_com/www/signup.html

[fix] group relative fields

---

erpnext_com/templates/includes/custom.css
erpnext_com/templates/includes/footer/footer.html
erpnext_com/www/about.html
erpnext_com/www/index.html
erpnext_com/www/pricing/index.html
erpnext_com/www/privacy.md
erpnext_com/www/signup.html
erpnext_com/www/terms.md

Also, fix target _blank terms and privacy links to open in a new tab.

Update privacy, terms, ERPNext Cloud -> Frappe Cloud

---

erpnext_com/templates/includes/subscription.js
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

Password strength mandatory, recategorize company

---

erpnext_com/www/pricing/index.html

- min height for customization div

[fix] Inclusive of taxes

---

erpnext_com/api.py
erpnext_com/www/signup.html

- Added phone number field in signup form
- Added phone number field to `signup()` in `api.py`

Added phone number field in signup

---

erpnext_com/www/security/index.md

add a link to the cve references page

fix(security): add references link

---

erpnext_com/www/docs/user/videos/learn/workflow.md

Co-authored-by: parsimonyERP <38265755+parsimonyERP@users.noreply.github.com>

made grammatical changes

---

erpnext_com/www/docs/user/manual/en/introduction/implementation-strategy.md

- Update trial period from 30 days to 14 days
- update the link to "Getting started" page

Update trial period, fix broken link

---

erpnext_com/www/docs/user/manual/en/index.md

fix Healthcare link

---

erpnext_com/www/docs/user/manual/en/stock/item.md

fix: bullet points

---

erpnext_com/www/mobile.html

Fix mobile hero image

---

erpnext_com/www/pricing/index.html

Because in-app support has been disabled.

[Update] Replaced "in-app"

---

erpnext_com/www/docs/index.md

Changed the trial period in the description from 30 to 14 days.

Update erpnext.com trial period

---

erpnext_com/www/docs/user/manual/en/setting-up/articles/setup-two-factor-authentication.md

`set-config` was missing from the command

Bench command correction

---

erpnext_com/docs_to_pdf.py
erpnext_com/templates/includes/navbar/navbar_items.html
erpnext_com/www/docs/user/manual/en/stock/articles/stock-entry-purpose.md

```bash
▶ bench --site erpnext-docs execute erpnext_com.docs_to_pdf.execute
/Users/netchampfaris/frappe-bench/sites/erpnext-manual.md
▶ pandoc ./sites/erpnext-manual.md -o erpnext-manual.pdf
```

Script to convert manual to pdf

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/index.md

Addition of the plaid documentation link

fix: Update erpnext integration index.md

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/plaid_integration.md

This fixes the readability of the Plaid keys.

fix: make keys readable in markdown

---

erpnext_com/hooks.py
erpnext_com/public/js/search_docs.js

Add search to docs

---

erpnext_com/www/docs/user/manual/en/human-resources/job-applicant.md

Updated broken URL for job-opening

Broken job-opening URL

---

erpnext_com/www/docs/user/manual/en/human-resources/recruitment-intro.md

Recruitment page - staffing plan Broken URL

Recruitment page - staffing plan Broken URL

---

erpnext_com/www/enterprise.html

Target blank opens as popup in some browsers which can be blocked

fix: Remove target blank

---

erpnext_com/www/docs/user/manual/en/human-resources/recruitment-intro.md

Recruitment page - Broken URL

---

erpnext_com/www/docs/user/manual/en/human-resources/recruitment-intro.md

Reverts frappe/erpnext_com#336

Revert "Recruitment page - Broken URL"

---

erpnext_com/www/docs/user/manual/en/setting-up/feedback/index.md
erpnext_com/www/docs/user/manual/en/setting-up/feedback/manual-feedback-request.md
erpnext_com/www/docs/user/manual/en/setting-up/feedback/resend-feedback-request.md
erpnext_com/www/docs/user/manual/en/setting-up/feedback/setting-up-feedback.md
erpnext_com/www/docs/user/manual/en/setting-up/feedback/submit-feedback.md

Frappe: https://github.com/frappe/frappe/pull/7463
ERPNext: https://github.com/frappe/erpnext/pull/17579
Docs: https://github.com/frappe/erpnext_com/pull/343

fix: Mark Feedback Trigger as removed in Version 12

---

erpnext_com/erpnext_com/doctype/cve_report_form/cve_report_form.py

create issues on frappe.erpnext.com as soon as a cve is reported

feat(cve_report_form): make issues from cve reports

---

erpnext_com/www/docs/user/manual/en/accounts/multi-currency-accounting.md

Changed the api reference from fixer to Frankfurter

Fix Currency Exchange API reference

---

erpnext_com/www/docs/user/manual/en/regional/india/auto-generate-e-way-bill-JSON.md

Existing docs: https://erpnext.com/docs/user/manual/en/regional/india/auto-generate-e-way-bill-JSON

fix: update docs for changed button location, add screenshot class to images

---

erpnext_com/www/docs/user/manual/en/manufacturing/introduction.md

docs: Update Manufacturing module

---

erpnext_com/www/docs/user/manual/en/customize-erpnext/customize-form.md
erpnext_com/www/docs/user/manual/en/setting-up/integrations/gocardless-integration.md
erpnext_com/www/docs/user/manual/en/stock/articles/creating-depreciation-for-item.md

make the doc pages responsive

---

erpnext_com/www/docs/user/manual/en/accounts/subscription.md

docs: improve list of steps view in point 1

---

erpnext_com/www/about.html

Changed the spelling on erpnext.com/about

fix: spelling

---

erpnext_com/www/docs/user/manual/en/education/setting-up-lms.md

corrected spellings of misspelt words.

docs: spelling corrections in setting-up-lms.md

---

erpnext_com/www/docs/user/manual/en/CRM/opportunity.md

Explanation - Minutes to First Response  feature working

Feature Minutes to First Response

---

erpnext_com/www/docs/user/manual/en/stock/stock-entry.md

Added Link for Stock Entry  purpose Material Consumption for Manufacture

Stock Entry : Material Consumption for Manufacture

---

erpnext_com/www/docs/user/manual/en/stock/accounting-of-inventory-stock.md
erpnext_com/www/docs/user/manual/en/stock/articles/migrate-to-perpetual-inventory.md
erpnext_com/www/docs/user/manual/en/stock/perpetual-inventory.md

update perpetual inventory docs

---

erpnext_com/www/docs/user/manual/en/human-resources/leave-type.md

**Fixes:** incorrect description of the field

fix: max continuous leaves allowed

---

erpnext_com/www/privacy/index.html
erpnext_com/www/privacy/policy.md

- Move privacy.md to policy.md
- Add data download and deletion links
- Update policy.md file
<details>
<summary>Privacy Landing Page</summary>
</details>
<details>
<summary>Webform for data download request</summary>
</details>
<details>
<summary>Webform for data deletion request</summary>
</details>
<details>
<summary>Policy Page</summary>
</details>
Dependent on: https://github.com/frappe/central/pull/792

docs: Add privacy landing page

---

erpnext_com/www/docs/user/manual/en/human-resources/attendance.md
erpnext_com/www/docs/user/manual/en/human-resources/auto-attendance.md
erpnext_com/www/docs/user/manual/en/human-resources/index.md

added a single page Introduction Auto Attendance.
Screenshot:

Docs(HR): Introduction Page for Auto Attendance

---

erpnext_com/templates/includes/footer/footer.html
erpnext_com/www/version-12/index.html
erpnext_com/www/version-12/release-notes/index.md

feat: added all links for v12

---

erpnext_com/www/docs/user/manual/en/human-resources/attendance.md
erpnext_com/www/docs/user/manual/en/human-resources/auto-attendance.md

minor visual changes to auto attendance docs.
**before:**
**after:**

fix(HR docs): minor fixes in auto attendance docs

---

erpnext_com/www/pricing/faq.html
erpnext_com/www/pricing/index.html

- Basically, will help improve SEO when it comes to our FAQ pages. For more details, refer: https://developers.google.com/search/docs/data-types/faqpage
- Also linked FAQ page to pricing

feat: added rich results FAQ structure via JSON-LD

---

erpnext_com/www/pricing/faq.html

fix: change styling of the last contact line

---

erpnext_com/www/docs/user/manual/en/hospitality/index.md

order entry and hotel room link fix

---

erpnext_com/www/docs/user/manual/en/using-erpnext/to-do.md

updated assignments feature link

fix: broken link

---

erpnext_com/www/docs/user/manual/en/accounts/tax-withholding-category.md

Corrected image link for Tax Withholding Category

docs: Update tax-withholding-category.md

---

erpnext_com/www/version-12/index.html

Pricing page introduces more friction to those wanting to signup

fix: Update sign-up link to Standard Plan

---

erpnext_com/templates/includes/footer/footer.html

Updated link from erpnext.org/docs/user/manual/en to /docs

Update docs link to new page

---

erpnext_com/public/css/rotate.css
erpnext_com/public/js/rotate.js
erpnext_com/templates/includes/card_grid.html
erpnext_com/www/docs/user/manual/en/human-resources/index.html
erpnext_com/www/index.html

Updated hero animation
Home Page Changes

feat: minor designs updates

---

erpnext_com/www/privacy/policy.md

Removed older policy update date of October 2018

remove old policy update date

---

erpnext_com/www/pricing/index.py

fix: Change minimum users to 100 for self-hosted

---

erpnext_com/www/index.html

Replaced the documentation links with feature pages in the cards

fix: Update links

---

erpnext_com/www/docs/user/manual/en/setting-up/articles/managing-perm-level.md

Corrected Typos and added some additional sentence for better understanding, after talking to Basawaraj, Ketan.

Doc: Typo-Fix & Additions

---

erpnext_com/www/docs/user/manual/en/website/web-form.md

remove pagination from feature list of web forms since it was removed in version 12

remove pagination from webforms

---

erpnext_com/www/docs/user/manual/en/human-resources/contents.md

Updating topics from H5 to H3 as they are in the rest of the docs

fix: topic headings

---

erpnext_com/www/docs/user/manual/en/accounts/purchase-invoice.md
erpnext_com/www/docs/user/manual/en/accounts/sales-invoice.md

- Fix typo
- Remove trailing whitespace

docs: fix typo

---

erpnext_com/www/docs/user/manual/en/setting-up/email/email-account.md

style: updated bullet points view + consistency

---

erpnext_com/www/index.html

For consistency of feature page cards in Index, Feature Page and Landing Page

fix: Update feature page in index

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/contents.md

* Add Google Drive to Backup section
* Mark Google Drive in Google section with "(Only Backup)"
* Number the points

Google Drive is for backup only

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/plaid_integration.md

"Please check their [FAQ](https://plaid.com/docs/faq/#does-plaid-support-international-bank-accounts-) to see if your country is supported."

feat(plaid): add note on availability

---

erpnext_com/www/docs/user/manual/en/customize-erpnext/server-script.md

Support Before/After Save for submitted document

docs(server scripts): Support Before/After Save for submitted document

---

erpnext_com/www/docs/user/manual/en/education/student.md

Changes the word "detials" to "details".

Fixes spelling error

---

erpnext_com/www/docs/user/manual/en/setting-up/email/email-account.md
erpnext_com/www/docs/user/manual/en/setting-up/email/email-domain.md

relevant feature: https://github.com/frappe/frappe/pull/9039

feat(email_ssl): add documentation for outgoing ssl

---

erpnext_com/www/docs/user/manual/en/selling/blanket-order.md

There was a spelling mistake in title.

Spelling mistake in title

---

erpnext_com/www/docs/user/manual/en/website/product-page.md

add details about Website Warehouse

update product page in website

---

erpnext_com/www/docs/index.html

Fixed various spelling errors and typos.

bug: Correction of various spelling errors.

---

erpnext_com/templates/includes/footer/footer.html

Updated footer links for "Manufacturing" & "Customer Stories"

fix: Update footer links

---

erpnext_com/www/docs/user/manual/en/setting-up/energy-point-system.md

add more details for user field -  Modified By

update energy points docs

---

erpnext_com/www/docs/user/manual/en/automation/auto-repeat.md

Added docs for enabling "Allow Print for Draft" in Print Settings to enable attaching recurring document created in the Auto Repeat Notification mail:

docs: auto repeat notification mail permission issue

---

erpnext_com/www/index.html

- Reduced content of Open Graph Protocol meta tags (og:title, og:description)
- Added OG meta tags (og:type, og:site_name, og:image)
- Updated Twitter Card

fix: Meta tags

---

erpnext_com/www/docs/user/manual/en/accounts/journal-entry.md

Company and Accounts module doesn't exists in the latest version. Journal Entry  has been moved to General Ledger Section

docs: Journal Entry module path

---

erpnext_com/www/docs/user/manual/en/accounts/articles/how-to-freeze-accounting-ledger.md
erpnext_com/www/docs/user/manual/en/accounts/articles/how-to-manage-subscriptions-with-erpnext.md
erpnext_com/www/docs/user/manual/en/accounts/articles/post-dated-cheque-entry.md
erpnext_com/www/docs/user/manual/en/accounts/bank-guarantee.md
erpnext_com/www/docs/user/manual/en/accounts/bank-reconciliation.md
erpnext_com/www/docs/user/manual/en/accounts/budgeting.md
erpnext_com/www/docs/user/manual/en/accounts/cost-center.md
erpnext_com/www/docs/user/manual/en/accounts/fiscal-year.md
erpnext_com/www/docs/user/manual/en/accounts/inter-company-journal-entry.md
erpnext_com/www/docs/user/manual/en/accounts/payment-reconciliation.md
erpnext_com/www/docs/user/manual/en/accounts/purchase-invoice.md
erpnext_com/www/docs/user/manual/en/accounts/sales-invoice.md
erpnext_com/www/docs/user/manual/en/accounts/share-reports.md
erpnext_com/www/docs/user/manual/en/accounts/share-transfer.md
erpnext_com/www/docs/user/manual/en/accounts/shareholder.md
erpnext_com/www/docs/user/manual/en/accounts/subscription-plan.md
erpnext_com/www/docs/user/manual/en/accounts/subscription-settings.md
erpnext_com/www/docs/user/manual/en/accounts/subscription.md
erpnext_com/www/docs/user/manual/en/accounts/tax-rule.md
erpnext_com/www/docs/user/manual/en/human-resources/expense-claim.md
erpnext_com/www/docs/user/manual/en/introduction/concepts-and-terms.md
erpnext_com/www/docs/user/manual/en/projects/project-profitability.md
erpnext_com/www/docs/user/manual/en/setting-up/articles/delete-a-company-and-all-related-transactions.md
erpnext_com/www/docs/user/manual/en/stock/articles/mode_of_payment.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/letter-head-in-the-report.md
erpnext_com/www/docs/user/manual/en/website/coupon-code.md
erpnext_com/www/docs/user/manual/es/accounts/advance-payment-entry.md

fix path names accounting

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/amazon_integration.md

docs(amazon-integration): update mws documentation with warning for certain use cases

---

erpnext_com/www/docs/user/manual/en/accounts/articles/merging-accounts.md
erpnext_com/www/docs/user/manual/en/using-erpnext/Global-search.md
erpnext_com/www/docs/user/manual/en/using-erpnext/access-log.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/adding-attachments-to-outgoing-messages.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/attachment-of-files.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/bulk-rename.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/check-link-between-documents.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/copy-pasting-multiple-records-from-excel.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/letter-head-in-the-report.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/todo-auto-creation.md
erpnext_com/www/docs/user/manual/en/using-erpnext/articles/tree-master-renaming.md
erpnext_com/www/docs/user/manual/en/using-erpnext/assignment.md
erpnext_com/www/docs/user/manual/en/using-erpnext/calendar.md
erpnext_com/www/docs/user/manual/en/using-erpnext/collaborating-around-forms.md
erpnext_com/www/docs/user/manual/en/using-erpnext/contents.md
erpnext_com/www/docs/user/manual/en/using-erpnext/desktop.md
erpnext_com/www/docs/user/manual/en/using-erpnext/document-versioning.md
erpnext_com/www/docs/user/manual/en/using-erpnext/filter-by.md
erpnext_com/www/docs/user/manual/en/using-erpnext/notes.md
erpnext_com/www/docs/user/manual/en/using-erpnext/restore-deleted-docs.md
erpnext_com/www/docs/user/manual/en/using-erpnext/save-filter.md
erpnext_com/www/docs/user/manual/en/using-erpnext/search-filter.md
erpnext_com/www/docs/user/manual/en/using-erpnext/to-do.md
erpnext_com/www/in-app-support.md
erpnext_com/www/india-gst.html
erpnext_com/www/introducing-in-app-support.md

in using-erpnext + in app support page

fix typos and grammar errors

---

erpnext_com/www/docs/user/manual/en/CRM/index.html

fix broken path from index.html

fix path in appointment

---

erpnext_com/www/docs/user/manual/en/using-erpnext/index.html

Fixed broken links for Search Filter and Save Filter
Updated Text and grammatical corrections for Search Filter

Update index.html - Fixed broken links

---

erpnext_com/www/docs/user/manual/en/stock/serial-no.md

doc: update to serial-no.md

---

erpnext_com/www/docs/user/manual/en/healthcare/patient.md

Updated broken link for Custom Print Format.
https://erpnext.com/docs/user/manual/en/healthcare/patient?ref=Patient%20Repository

doc: update patient.md

---

erpnext_com/www/privacy/index.html

Increased the length of the meta description

fix: privacy page meta tags

---

erpnext_com/www/privacy/index.html

Reverts frappe/erpnext_com#699

Revert "fix: privacy page meta tags"

---

erpnext_com/www/contact.html

Added meta tags to Contact Us page of erpnext.com website

fix: Add meta tags to Contact Us page

---

erpnext_com/www/support/index.html

Added meta tags to Support Page of erpnext.com website

fix:Add meta tags to Support Page

---

erpnext_com/www/privacy/index.html

Added meta tags for Privacy Page of erpnext.com website

fix: Add meta tags to Privacy Page

---

erpnext_com/www/index.html

Reduced the meta title length (now 160 characters)

fix: meta title too long

---

erpnext_com/www/version-12/release-notes/features.md

Meta tag description was identical to index.md; changing the description to keep it unique
~SEO

fix: change meta tag description

---

erpnext_com/www/docs/user/manual/en/accounts/payment-entry.md

Payment entry:- Removed Extra Brackets
Blanket Order:- Solved Conflicts

fix: Payment Entry and Blanket Order 

---

erpnext_com/www/docs/user/manual/en/human-resources/additional-salary.md

feat(docs): Recurring Additional Salary

---

erpnext_com/www/docs/user/manual/en/education/contents.md

Updated link to Assessment Result tool 
Uncommented Course Scheduling tool

Update contents.md with broken links

---

erpnext_com/www/docs/user/manual/en/human-resources/auto-attendance.md
erpnext_com/www/docs/user/manual/en/setting-up/articles/integrating-erpnext-with-biometric-attendance-devices.md
erpnext_com/www/docs/user/manual/en/setting-up/contents.md

This PR adds an article for biometric integration and steps to setup auto attendance.
- The Article
- Auto Attendance Setup

Docs: biometric integration article

---

erpnext_com/www/support/index.html

chore: remove pricing for self hosted plan

---

.github/workflows/nodejs.yml
.travis.yml
.travis/spell_checker.sh

Add GitHub Action for spell-check and [remove Travis build](https://github.com/frappe/erpnext_com/pull/717).
Info:
- To ignore a folder from spell check, add an entry in `ignorePaths` in `spell_checker/cSpell.json`
- To ignore a word from spell-check add that word to `spell_checker/cspell_ignored_words.txt`
- [More information](https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#how-it-works) related to spell-checker lib

chore: Add Github Action for spell-check

---

erpnext_com/hooks.py

feat: add partner login option

---

erpnext_com/www/docs/user/videos/learn/shopping-cart.md

The spelling of `allows` and `orders` where having errors.

Fixed typos.

---

erpnext_com/www/docs/user/manual/en/setting-up/company-setup.md

docs: Update company master

---

erpnext_com/www/docs/user/manual/en/customize-erpnext/articles/table-multiselect-field.md

Saw it from https://github.com/frappe/frappe/issues/8888#issuecomment-578011759
Tested and it works.

In List View is mandatory

---

erpnext_com/www/docs/user/manual/en/stock/item.md

update item master

---

erpnext_com/www/docs/user/manual/en/stock/stock-entry.md

add details about expense account

update stock entry

---

erpnext_com/www/docs/user/manual/en/support/maintenance-visit.md

docs: fixed maintenance visit

---

erpnext_com/www/docs/user/manual/en/erpnext_integration/shopify_integration.md

docs: shopify settings

---

erpnext_com/www/docs/user/manual/en/accounts/period-closing-voucher.md

docs: Update period-closing-voucher.md

---

erpnext_com/www/docs/user/manual/en/accounts/opening-balance/current_assets.md

credit changed to debit (check screenshot too)

docs: current asset

---

erpnext_com/www/docs/user/manual/en/accounts/cost-center.md

docs: update cost center

---

erpnext_com/www/docs/user/manual/es/accounts/index.md

Update accounts index spanish

---

erpnext_com/www/docs/user/manual/de/erpnext_integration/index.md
erpnext_com/www/docs/user/manual/de/erpnext_integration/index.txt
erpnext_com/www/docs/user/manual/de/erpnext_integration/ldap-integration.md

Translation of the [English docs](https://erpnext.com/docs/user/manual/en/erpnext_integration/ldap-integration).

feat(german docs): add LDAP integration

---

erpnext_com/templates/includes/signup_footer.html

Depends on: [665](https://github.com/frappe/erpnext_com/pull/665)

fix: Replace PNG images with SVG images

---

erpnext_com/www/docs/user/manual/en/human-resources/job-applicant.md

docs: update job applicant

---

erpnext_com/www/docs/user/manual/en/index.html

feat: Add searchbar in manual

---

erpnext_com/templates/includes/signup_footer.html

Reverts frappe/erpnext_com#666

Revert "fix: Replace PNG images with SVG images"

---

erpnext_com/www/pricing/index.py

https://github.com/frappe/central/pull/1075

fix: round up total to nearest 10 if pricing multiplier exists

---

erpnext_com/www/pricing/index.py

https://github.com/frappe/central/pull/1074

feat: provision to accommodate new pricing

---

erpnext_com/hooks.py
erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

feat: remove standard plan

---

erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

feat: show discounted price on pricing page

---

erpnext_com/www/index.html

add fb business verify

---

erpnext_com/www/pricing/index.py

feat: remove onboarding support hrs from pricing page

---

erpnext_com/www/pricing/index.html
erpnext_com/www/pricing/index.py

fix: Update onboarding hours on Pricing Page
